apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: valkeybackups.valkey.andino.io
  labels:
  {{- include "valkey-operator.labels" . | nindent 4 }}
spec:
  group: valkey.andino.io
  names:
    kind: ValkeyBackup
    listKind: ValkeyBackupList
    plural: valkeybackups
    singular: valkeybackup
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ValkeyBackup is the Schema for the valkeybackups API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of ValkeyBackup
            properties:
              cronjob:
                description: Configuration for the cronjob that manages the backup schedule.
                properties:
                  enabled:
                    default: false
                    description: Enable or disable the cronjob.
                    type: boolean
                  schedule:
                    description: The cron schedule for the backup job.
                    pattern: ^(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every
                      (\d+(ns|us|µs|ms|s|m|h))+)|((\d+|\*) (\d+|\*) (\d+|\*) (\d+|\*)
                      (\d+|\*))$
                    type: string
                  sleep_before_exec:
                    default: 0
                    description: Defines the amount of seconds to wait before the execution
                      starts
                    type: integer
                type: object
              image:
                description: Configuration for the container image used for the backup.
                properties:
                  debug:
                    default: false
                    description: Enable debug mode for the image.
                    type: boolean
                  repository:
                    description: The image repository.
                    type: string
                  tag:
                    description: The image tag.
                    type: string
                required:
                - repository
                - tag
                type: object
              namespace:
                description: The namespace where the backup will be created.
                type: string
              restic_password:
                description: Secret with the password for the Restic repository.
                type: string
              restore:
                description: Configuration needed for the proper restore of a backup
                properties:
                  enabled:
                    description: Enable the restore. This will be executed as a job
                      and the cronjob has to be set as false
                    type: boolean
                  show_available_backups:
                    description: List all the backups availables to restore. Optional
                    type: boolean
                  snapshot_id:
                    description: Provide this if known the snapshot id, if not it will
                      be restored the last snapshot. Optional
                    type: string
                type: object
              s3:
                description: Configuration for the S3 storage backend.
                properties:
                  access_credentials_secret:
                    description: The name of the secret with the access_key and secret_access_key
                      for S3
                    type: string
                  bucket_name:
                    description: The name of the S3 bucket.
                    type: string
                  host:
                    description: The host address of the S3 service.
                    type: string
                  port:
                    default: 443
                    description: The port of the S3 service.
                    type: integer
                  region:
                    description: The region of the S3 bucket.
                    type: string
                  use_ssl:
                    default: true
                    description: Enable SSL for the S3 connection.
                    type: boolean
                required:
                - access_credentials_secret
                - bucket_name
                - region
                - host
                - port
                - use_ssl
                type: object
              valkey:
                description: Configuration for the Valkey instance.
                properties:
                  architecture:
                    default: standalone
                    description: Describe the type of valkey where the instance will
                      be connected
                    type: string
                  certificates_secret:
                    description: The name of the secret containing TLS certificates
                    type: string
                  use_tls:
                    default: false
                    description: Enable TLS for Valkey connections.
                    type: boolean
                type: object
              valkey_instance_name:
                description: The name of the source valkey instance to make a backup
                type: string
            required:
            - valkey_instance_name
            - s3
            - restic_password
            type: object
          status:
            description: Status defines the observed state of ValkeyBackup
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []