apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "valkey-operator.fullname" . }}-valkeybackup-viewer-role
  labels:
  {{- include "valkey-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - valkey.andino.io
  resources:
  - valkeybackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - valkey.andino.io
  resources:
  - valkeybackups/status
  verbs:
  - get