apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
# We need to manage Helm roles
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  verbs:
  - "*"
# We need to manaje Jobs and Cronjobs
- apiGroups:
  - "batch/v1"
  resources:
  - jobs
  - cronjobs
  verbs:
  - "*"

##
## Rules for valkey.andino.io/v1alpha1, Kind: Valkey
##
- apiGroups:
  - "policy"
  resources:
  - poddisruptionbudgets
  verbs:
  - "*" 

- apiGroups:
  - "networking.k8s.io"
  - ""
  resources:
  - networkpolicies
  - configmaps
  verbs:
  - get
  - list
  - create
  - delete
  - patch
  - watch
  - update


- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - create
  - delete
  - patch
  - watch
  - update

- apiGroups:
  - valkey.andino.io
  resources:
  - valkeys
  - valkeys/status
  - valkeys/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

##
## Rules for valkey.andino.io/v1alpha1, Kind: ValkeyBackup
##
- apiGroups:
  - valkey.andino.io
  resources:
  - valkeybackups
  - valkeybackups/status
  - valkeybackups/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# +kubebuilder:scaffold:rules
