# permissions for end users to view valkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/managed-by: kustomize
  name: valkey-viewer-role
rules:
- apiGroups:
  - valkey.andino.io
  resources:
  - valkeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - valkey.andino.io
  resources:
  - valkeys/status
  verbs:
  - get
