# Default values for valkeybackup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# This parameter is required.
# Name of the instance to connect and backup
#valkey_instance_name: valkey-sentinel-ssl

#namespace: default

#Docker image to be used 
image: 
  repository: quay.io/david_andino/valkeybackup
  tag: latest
  #debug: false

cronjob:
  # if enabled you can customize the schedule time, if disabled then it will run just a job (used for testing purposes)
  enabled: false
  # if amount of time in seconds to wait before it starts the execution
  #sleep_before_exec: 0
  # ┌───────────── minute (0 - 59)
  # │ ┌───────────── hour (0 - 23)
  # │ │ ┌───────────── day of the month (1 - 31)
  # │ │ │ ┌───────────── month (1 - 12)
  # │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday)
  # │ │ │ │ │                                   OR sun, mon, tue, wed, thu, fri, sat
  # │ │ │ │ │
  # │ │ │ │ │
  # * * * * *
  # If not assigned will be added to every midnight
  #schedule: "0 0 * * *"

valkey:
  use_tls: "false"
  architecture: "standalone" # it can be standalone, replication or sentinel
  # The secret certificate has to contain the following data: ca.crt, tls.crt and tls.key
  #certificates_secret: secret_name_with_certificates

# Password of the restic which is required,
# This must to be saved in a secret with the key word: password
restic_password: my-restic-secret

# Required S3 connection information
# 
#s3:
#  #Access Key and Secret credential stores in a secret file
#  #The secret has to contain the access_key and secret_access_key as keys and each values.
#  access_credentials_secret:
#  bucket_name:
#  region:
#  host:
#  port:
#  use_ssl: # true or false
#
# Required for restore
# The restore steps has priority over the backups. 
# If the restore is enabled, no backup will be performed only the restore.
# Use it carefully.
# By design, the restore is only working as a normal JOB, so the cronjob should be set to enabled: false
# Test it first before doing any regular operation with it.
restore:
  enabled: false
  #show_available_backups: false # it can be chosen from: true or false, no restore will be done, only information displayed
  #snapshot_id: # Provide this if known the snapshot id, if not it will be restored the last snapshot


