apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-internal-kubectl-role
  namespace: {{ .Values.namespace  | default "default" }}
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  - pods/exec
  - persistentvolumeclaims
  verbs: ["get", "list", "watch","create","delete"]
- apiGroups: 
  - "valkey.andino.io"
  resources:
  - valkeys
  verbs: ["get", "list", "watch","delete","create","patch"]
