apiVersion: valkey.andino.io/v1alpha1
kind: ValkeyBackup
metadata:
  name: valkey-standalone-backup
spec:
  valkey_instance_name: valkey-standalone
  restic_password: valkey-restic-password
  valkey:
    use_tls: false
  cronjob:
    enabled: true
    schedule: "34,40,45 13 * * *"
  s3:
    access_credentials_secret: "s3-credentials-valkeybackup"
    bucket_name: "example-bucket-name"
    region: "my-example-region"
    host: "s3.example.host"
    port: 443
    use_ssl: true # true or false
---
apiVersion: valkey.andino.io/v1alpha1
kind: ValkeyBackup
metadata:
  name: valkey-standalone-ssl-backup
spec:
  valkey_instance_name: valkey-standalone-ssl
  restic_password: valkey-restic-password
  cronjob:
    enabled: true
    schedule: "34,40,45 13 * * *"
  valkey:
    use_tls: true
    certificates_secret: valkey-single-tls-cert
  s3:
    access_credentials_secret: "s3-credentials-valkeybackup"
    bucket_name: "example-bucket-name"
    region: "my-example-region"
    host: "s3.example.host"
    port: 443
    use_ssl: true # true or false
---
apiVersion: valkey.andino.io/v1alpha1
kind: ValkeyBackup
metadata:
  name: valkey-sentinel-ssl-backup
spec:
  valkey_instance_name: valkey-sentinel-ssl
  restic_password: valkey-restic-password
  cronjob:
    enabled: true
    sleep_before_exec: 0
    schedule: "40,45 13 * * *"
  valkey:
    use_tls: true
    architecture: sentinel
    certificates_secret: valkey-sentinel-replication-tls-cert
  s3:
    access_credentials_secret: "s3-credentials-valkeybackup"
    bucket_name: "example-bucket-name"
    region: "my-example-region"
    host: "s3.example.host"
    port: 443
    use_ssl: true # true or false
---
apiVersion: valkey.andino.io/v1alpha1
kind: ValkeyBackup
metadata:
  name: valkey-sentinel-backup
spec:
  valkey_instance_name: valkey-sentinel
  restic_password: valkey-restic-password
  cronjob:
    enabled: true
    sleep_before_exec: 0
    schedule: "34,40,45 13 * * *"
  valkey:
    use_tls: false
    architecture: sentinel
  s3:
    access_credentials_secret: "s3-credentials-valkeybackup"
    bucket_name: "example-bucket-name"
    region: "my-example-region"
    host: "s3.example.host"
    port: 443
    use_ssl: true # true or false

