apiVersion: valkey.andino.io/v1alpha1
kind: Valkey
metadata:
  name: valkey-sentinel
spec:
  architecture: replication
  sentinel:
    enabled: true
    quorum: 2
  auth:
    enabled: true
    password: test_pwd
